### ISSUE TITLE
Heritage Asset - Digital Object name not correctly displaying

### ISSUE THREAD

**Issue by chrisdolby-HE** [archesproject/Arches_HER#815] opened 2022-02-02 19:07 UTC
Associated Digital Files -> Digital Files
Created a new Digital File through the ‘Create new Digital Object’ (Just name and file type), but the name is not showing in the Heritage Asset tree, instead it has the value "\<Name>".

<img width="452" alt="image" src="https://user-images.githubusercontent.com/59013689/152217045-eae04fa3-5d0d-442a-86a6-4a0ea6d5f7b1.png">

**Comment by chiatt** [comment] 2022-03-18 20:13
Reindexing may clear up this problem

**Comment by chiatt** [comment] 2022-03-29 21:14
Hey @chrisdolby-HE, I'm not able to reproduce this using the latest graph because the Associated Digital File node is now a `resource-instance-list` rather than a `resource-instance` node. 

![image](https://user-images.githubusercontent.com/1877663/160707851-636abae1-d608-4247-ac7f-793b0ae31063.png)

I tried to reproduce the issue using other resource-instance nodes, but no luck. I'm going to close this ticket, but if you see the issue pop up again elsewhere, please reopen.

**Closed as completed by chiatt** 2022-03-29 21:14 UTC
Labels: bug
